Step1
2023newkrew/jwp-was-kakao pull request #12
Opened 2023-02-06 09:55 UTC by Siryeong

니오 안녕하세요 :)
웹서버 구현 미션의 리뷰요청을 드립니다.
항상 시간내어 좋은 리뷰 남겨주셔서 감사합니다!
😘😘😘

2023-02-06 15:57 UTC, sehan requested changes
안녕하세요 davi 

request 처리를 위한 로직분리를 아주 멋지게 처리해주셨습니다. 👍
다만, request 메세지를 파싱하는 부분에 대한 테스트코드가 부족하여 테스트를 보강해보면 좋을거 같습니다. 

개선요청드립니다. 

코드에 남겨둔 다른 코멘트들은 이후 미션진행시 참고하시면 좋을거 같습니다.

2023-02-06 15:57 UTC, sehan commented on src/main/java/webserver/WebServer.java
> +                                new UserController()
ResourceController, UserController 가 thread safe 하다면 request 마다 생성하지 않고 하나의 객체를 생성해서 재사용해도 될거 같습니다.

2023-02-06 15:57 UTC, sehan commented on src/main/java/webserver/RequestHandler.java
> +    public RequestHandler(Socket connectionSocket, ResourceController resourceController, UserController userController) {
request 처리 역할을 Controller 로 잘 분리하셨네요 👍

2023-02-06 15:57 UTC, sehan commented on src/main/java/http/HttpRequestParser.java
> +        );
http rfc 에서 Request 는, Request-LIne, *Header, Message-body 로 구성하고 있습니다.  HttpRequestHeader 클래스는 Request-Line 과 Header 들을 담고 있어서 의미상 혼란의 여지가 있습니다. rfc 규격과 구현 클래스가 일치하면 코드를 이해하는데 더 도움이 될거 같습니다. 

https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

2023-02-06 15:57 UTC, sehan commented on src/main/java/http/HttpRequest.java
> +    }
QueryString 을 사용한 회원가입을 POST 방식 회원가입으로 변경하면서 QueryString 처리 부분을 삭제한 것으로 보입니다.  미션의 의도는 QueryString 구현부분이 HttpRequest 객체에 남기를 바란것으로 생각합니다.  즉, HttpRequest 가 getParam() 같은 매소드를 제공해주면 좋지 않을까 생각합니다.

2023-02-06 15:57 UTC, sehan commented on src/main/java/model/User.java
> +    }
User.fromQueryString() 매소드를 사용하는 사람의 관점에서는 query 로 무엇이 들어와야 하는가?? 하는 의문이 있습니다.  즉, User 객체의 속성을 다 알고 있어야 query 를 어떻게 만들어 넣어야  User 객체를 정상적으로 만들 수 있습니다.  객체의 내부를 자세히 알지 못해도 매소드로 넘겨줄 query 가 어떤형태를 가져야 하는지 알 수 있어야 합니다. 그그리고 user 클래스는 도메인 모델에 속하기 때문에 query 에 의존하게 되면 QueryString 에 의존적이게 됩니다. QueryString 파싱하는 로직은 별도로 분리되거나 HttpRequest 를 통해서 제공되거나 하면 좋지 않을까요?

2023-02-06 15:57 UTC, sehan commented on src/main/java/http/HttpRequestParser.java
> +public class HttpRequestParser {
Parser 에 대한 테스트 코드가 없습니다.
http request message 파싱 테스트코드를 작성해주면 더 좋을거 같습니다. 
테스트를 작성하다보면 더 작은 단위로 분리해서 파싱 로직들을 테스트하기 쉽게 분리해 내면 좋겠습니다.

2023-02-06 15:57 UTC, sehan commented on src/main/java/controller/UserController.java
> +        User user = User.fromQueryString(query);
QueryString 을 처리하는 파싱 로직을 User 모델과 controller 에서 구현시점에 결정하고 있습니다.   http server 를 구현하는 미션의 성격으로 볼때 http server 가 어떤 부분까지 제공해줘야 할지 어떤 역할까지 책임을 져야 할지 고민해보면 좋을거 같습니다.  
이번 미션은 회원가입 로직을 구현하는것이 중요한것이 아니라 http server 를 구현하는것이 핵심입니다.

2023-02-07 06:12 UTC, Siryeong commented
니오 안녕하세요 :) 피드백 주신것 반영하여 수정해 보았습니다.
스프링에서 당연하게 사용하던 것들을 직접 구현해보니 놓치고 지나가는 부분이 참 많다는 생각이 드네요.
항상 좋은 리뷰 남겨주셔서 감사합니다!

2023-02-07 08:19 UTC, sehan approved these changes
요청드린 피드백을 너무 잘 반영해주셨습니다. 👍👍👍
다음 step 진행하면서 참고할 만한 코멘트를 남겨두었습니다.  

고생하셨습니다. 이번 step 은 merge 하도록 하겠습니다.

2023-02-07 08:19 UTC, sehan commented on src/main/java/controller/ResourceController.java
> +    }
의도적으로 싱글톤 객체로 만드는것도 방법이지만 WebServer 에서 Controller 객체를 생성해서 재사용해도 괜찮습니다.
Spring 을 생각해보면 우리가 Bean 으로 등록할때 해당 클래스를 싱글톤으로 구현하지 않는 것처럼 Controller 를 생성해서 Spring 이 Bean 을 관리하듯이 WebServer 가 Controller 객체의 생명주기를 관리해주는 방법도 고민해보면 좋겠습니다.

2023-02-07 08:19 UTC, sehan commented on src/main/java/http/HttpRequest.java
> +    public HttpRequest(HttpRequestLine httpRequestLine, HttpRequestHeader httpRequestHeader, HttpRequestBody httpRequestBody) {
👍

2023-02-07 08:19 UTC, sehan commented on src/main/java/http/QueryParser.java
> +public class QueryParser {
👍

2023-02-07 08:19 UTC, sehan commented on src/main/java/http/HttpRequestBody.java
> +        this.params = QueryParser.parse(this.content);
body 내용이 queryString 으로 들어온다는 보장은 없습니다.
현재 구현된 http server 의 스팩으로는 body 로 query string 만을 허용한다고 봐야겠네요 😊

2023-02-07 08:19 UTC, sehan commented on src/main/java/http/HttpRequest.java
> +        return Optional.empty();
POST 요청에도 /create/user?name=nio. 로 요청하면 param 으로 전달되기는 합니다. 하여 POST 는 body 에서 param 을 가져오고 GET 은 request-line 의 querystring 에서 param 을 가져오는것은 http rfc 스팩과 차이가 있기는 합니다.

2023-02-07 08:19 UTC, sehan commented on src/test/java/http/HttpRequestParserTest.java
> +class HttpRequestParserTest {
Request message 파싱 테스트 코드가 있으니 한결 좋지 않나요? 😊
👍👍👍

2023-02-07 08:19 UTC, merged