[red.is] Step1
2023newkrew/jwp-was-kakao pull request #14
Opened 2023-02-06 11:22 UTC by coolofficials

에디, 이번에 페어가 그레이라서 리뷰 한 번에 하시면 됩니다 ㅎㅎ

2023-02-07 05:35 UTC, eddy-oum requested changes

2023-02-07 05:35 UTC, eddy-oum commented on src/main/java/db/DataBase.java
> +    private static Map<String, User> users = new HashMap<>();
임시로 사용하는 용도인지, step 2에서도 사용하는 클래스인지는 모르겠습니다만,
여러 스레드가 동시에 접근할 수 있으므로, synchronized나 ConcurrentHashmap을 이용해주시면 좋겠습니다.

임시용도라면 그대로 두셔도됩니다.

2023-02-07 05:35 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +            }
request를 받아서 적절한 메소드를 호출하는 부분이네요.

스프링처럼 @RequestMapping 같은 어노테이션을 붙이면 해당 메소드가 호출되는 것을 요구하지는 않지만,
어떤 path는 ```(RequestReader req, ResponseWriter res) -> {}``` 형태의 handler를 호출한다라는 매핑이 어딘가에 있고, 이 run() 메소드는 해당 매핑을 충실히 따를 수 있으면 좋겠습니다.

핸들러는 inputstreamreader, dataoutputstream에 대해서 모를 수 있으면 좋을 것 같아요.

2023-02-07 05:43 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +                contentType = "text/html;charset=utf-8";
자바에서 지원하는 상수값들이 있을 것 같습니당.

2023-02-07 05:43 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +            if (line.startsWith("Content-Length: ")) {
자바에서 지원하는 상수값들이 있을 것 같습니당.

2023-02-07 05:45 UTC, eddy-oum commented
WebServer 클래스에서 요청 당 스레드를 새로이 생성해주고 있는데요, _시간이 남는다면_ 스레드 풀을 활용해보시는 것도 재밌을 것 같습니다.
성능비교까지 해보셔도 좋을 것 같네요.

2023-02-08 05:59 UTC, coolofficials commented on src/main/java/webserver/RequestHandler.java
> +                contentType = "text/html;charset=utf-8";
상수 못 찾았습니다.

2023-02-08 06:05 UTC, coolofficials commented on src/main/java/webserver/RequestHandler.java
> +            }
@eddy-oum 의도를 정확하게 파악하지 못해서요. 혹시 예시를 조금 들어주실 수 있을까요?

@abcworld123 는 아래와 같은 형태의 코드를 사용할 수 있도록 추상화하기를 원하시는 거라고 추측 중입니다.
`res.status(200).body("abc");
res.send("abc");`

2023-02-08 08:45 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +                contentType = "text/html;charset=utf-8";
네 openjdk에는 없고,
java ee나 import org.springframework.http.MediaType;
에 있네요.

2023-02-08 08:59 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +            }
과제의 목적인 WAS 중 하나인 tomcat은 자바의 servlet 인터페이스를 구현한 서블릿들의 컨테이너입니다.

httpservlet 은 그 중 http 요청을 처리하기 위한 서블릿들입니다.

https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html

http 서블릿에서는 ```service(HttpServletRequest req, HttpServletResponse resp)``` 라는 메소드가 있습니다.

RequestHandler 내부의

if (path.startsWith("...") {
    doStuff();
} else if (path.startsWith("..")) {
    doOtherStuff();
}

를

```java
HttpServlet sv = getServletFor(requestPath);
sv.service(req, res);
```
처럼 만들어주시고,

requestPath가 어떤 servlet에 매칭되는 지를 코드 외부로 뺴주시면 좋겠다라는 의미였습니다.

2023-02-08 09:08 UTC, eddy-oum commented on src/main/java/webserver/RequestHandler.java
> +            }
다만 오늘안에 머지되면 좋겠다라는 요청사항이 있었고, 오늘 안에 바꾸기에는 분량이 많을 것 같아서.. 여유가 되신다면 바꿔주시면 좋겠네요.
우선은 머지합니다.

2023-02-08 09:08 UTC, eddy-oum approved these changes

2023-02-08 09:08 UTC, merged