[jade.xyz] HTTP 웹서버 step1 과제 제출
2023newkrew/jwp-was-kakao pull request #29
Opened 2023-02-07 06:01 UTC by mincastle98

안녕하세요 제이든!

벌써 스프링 과제도 마무리되고 마지막 미션이네요.
이번 과제는 HTTP 웹 서버 구현 과제입니다.

스프링과 달리 웹 서버는 사전 지식이 많이 부족하고 어떤 흐름으로 진행되는지 잘 몰라서 코드가 많이 어색한 것 같습니다..
최대한 유연하게 구현한다고 했는데 잘 되지 않네요😭

- ControllerSelector를 통한 RequestMapping
- Request 헤더와 바디 추출
- 확장자에 따른 정적 resource 디렉토리 처리
- 각 처리에 따른 StatusCode 반환
등을 주로 구현했습니다.

마지막 미션까지 잘 부탁드립니다🙇🏻‍♂️

2023-02-08 02:42 UTC, jinuk17 requested changes
마지막 미션까지 고생많으셨어요  👍 👍 👍 
몇가지 개선 사항 리뷰 남겨두었습니다.
확인 후에 재요청 부탁드려요 🙏

2023-02-08 02:42 UTC, jayden-17 commented on README.md
> +## 요구사항 분석
요구사항 정리 !! 리뷰하는데 많은 도움이 됩니다 👍

2023-02-08 02:42 UTC, jayden-17 commented on src/main/java/controller/ControllerSelector.java
> +        if (request.getHeader().getHeaders().containsKey("Accept")) {
`Request`, `RequestHeader` 등이 모두 객체가 아닌 자료구조로만 사용되는 것 같아요 ~
객체로써 좀 더 책임을 부여해 볼 수 있지 않을까요 ?

2023-02-08 02:42 UTC, jinuk17 commented on src/main/java/controller/UserController.java
> +        return "";
빈문자열을 반환하는 것 보다는 void 로 반환하는게 어떨까요 ?

2023-02-08 02:42 UTC, jinuk17 commented on src/main/java/webserver/HttpMethod.java
> +public enum HttpMethod {
enum 👍

2023-02-08 02:42 UTC, jinuk17 commented on src/main/java/webserver/ResourceType.java
> +                .filter(v -> v.extensions.contains(extension))
값이 포함되었는지 확인하는 용도면 LIst 보다 Set 이 더 적절해 보여요 ~ 
List 와 Set 의 차이를 한번 확인해보면 좋을 것 같아요 ~

2023-02-08 02:42 UTC, jinuk17 commented on src/main/java/webserver/RequestParser.java
> +        ListIterator<String> iterator = request.listIterator();
어떤 목적으로 ListIterator 로 변환해서 사용하는 걸까요 ?

2023-02-08 02:42 UTC, jinuk17 commented on src/main/java/webserver/RequestParser.java
> +        while (iterator.hasNext()) {
stream API 를 이용해서 Map 으로 변환해 봐도 좋을것 같아요 ~ 
`Collectors.toMap()`

2023-02-08 08:06 UTC, mincastle98 commented on src/main/java/controller/UserController.java
> +        return "";
모든 메서드의 리턴값을 응답 형태를 정의한 BaseResponseDto에 담는데 void로 반환하면 responseBody 부분이 null이 되어서 빈 문자열을 반환하도록 하였습니다.
BaseResponseDto에서 Optional로 responseBody를 처리하도록 하는 방향으로 수정하고 void로 반환하도록 하는게 더 나은 방법일까요?

2023-02-08 08:08 UTC, mincastle98 commented on src/main/java/webserver/RequestParser.java
> +        ListIterator<String> iterator = request.listIterator();
구현 방식을 고민하다가 ListIterator의 previous()를 활용하는 과정이 있었는데 미처 변경하지 못했습니다. Iterator로 수정하였습니다!

2023-02-08 08:17 UTC, mincastle98 commented on src/main/java/controller/ControllerSelector.java
> +        if (request.getHeader().getHeaders().containsKey("Accept")) {
대부분 getter로 값을 가져와서 동작을 수행하고 있네요... 객체에 메시지를 던져서 동작을 수행하도록 수정해보았습니다!

해당 부분을 수정하면서 질문드릴 부분이 생겼는데요.

현재 Request가 필드로 RequestHeader를 가지고 있는 형태인데,
RequestHeader에 메시지를 던져야 할 때는 메서드를 어떻게 호출하는 것이 가장 나은 방법인지 고민이 되었습니다.
ex) getContentType을 호출해야 하는 경우 (RequestHeader의 역할로 생각되는 부분)
1. RequestHeader에 getContentType을 구현하고 Request에서 getter로 RequestHeader에 접근 후 메서드 호출
`request.getHeader().getContentType()`
2. RequestHeader에 getContentType을 구현하고 Request에 해당 메서드의 결과를 전달만 하는 메서드 구현
`request.getContentType()

public String getContentType() {
    return headers.getContentType;
}
`
3. Request에 getContentType을 구현, RequestHeader의 값이 필요할 때 getter로 접근

이렇게 3가지 방법이 있을 것 같은데, 3가지 방법 모두 장단점을 가지고 있는 것 같습니다.
현재는 첫번째 방법으로 구현하였는데 더 나은 방법이 있을까요?

2023-02-08 08:18 UTC, mincastle98 commented on src/main/java/webserver/RequestParser.java
> +        while (iterator.hasNext()) {
Stream을 활용하는 부분에서는 말씀해주신 Collectors.toMap()을 적용했는데 iterator에 stream을 적용하는 방법을 찾지 못해 해당 부분에는 적용하지 못했습니다😢

2023-02-08 08:20 UTC, mincastle98 commented
리뷰 남겨주신 부분 반영하여 코드 수정했습니다!
남겨주신 리뷰에 수정하면서 생긴 궁금증과 몇 가지 코멘트 남겨두었습니다. 
확인 후 답변 주시면 감사하겠습니다!

2023-02-08 12:01 UTC, brainbackdoor approved these changes
1단계 미션 진행하느라 수고했어요. 👍 
이미 리뷰어와 잘 소통하고 있는 것으로 보이는데요. 
1단계는 여기서 머지하고, 다음 단계를 진행해보는 건 어떨까요

2단계까지 마무리하고 유종의 미를 거두었으면 하는 바람으로 제가 대신 리뷰 진행해요.

2023-02-08 12:01 UTC, brainbackdoor commented on src/main/java/controller/ControllerSelector.java
> +        return new BaseResponseDto(StatusCode.NOT_FOUND,
수업때 이야기한대로 다형성을 활용하여 if 조건 분기를 없애보는 건 어떨까요

2023-02-08 12:01 UTC, brainbackdoor commented on src/main/java/webserver/RequestHandler.java
> +            RequestHeader requestHeader = RequestParser.parseHeader(requestStrings);
- BufferedReader로부터 문자열을 읽어내는 역할을 하는 객체 혹은 유틸성 클래스를 도출하는건 어떨까요?
- 메소드 내에서도 추상화 수준을 맞춰줄 필요가 있어 보입니다.

2023-02-08 12:01 UTC, brainbackdoor commented on src/main/java/webserver/RequestHandler.java
> +            }
프로그래밍 요구사항을 미준수하셨군요 😅

2023-02-08 12:02 UTC, merged

2023-02-08 12:03 UTC, brainbackdoor commented on src/main/java/controller/UserController.java
> +        return "";
BaseResponseDto 생성자에서 null 대응을 하는건 어떨까요?

2023-02-09 01:23 UTC, jinuk17 commented on src/main/java/webserver/RequestParser.java
> +        while (iterator.hasNext()) {
extractHeader 사용하는 코드에서 LIst 를 Iterator 로 변환하더라구요 ~ 
그 단계에서 Iterator 로 변환한 이유가 있을까요 ?

2023-02-09 01:24 UTC, jinuk17 commented on src/main/java/webserver/RequestParser.java
> +        ListIterator<String> iterator = request.listIterator();
그냥 `List<String> request` List 타입을 그대로 사용해도 되지 않을까 해서요 ~

2023-02-09 01:34 UTC, jinuk17 commented on src/main/java/controller/ControllerSelector.java
> +        if (request.getHeader().getHeaders().containsKey("Accept")) {
제가 2, 3번의 차이를 잘 이해하지 못했어요 ~ 

ContentType 을 더 많이 소비하는 곳이 어딘지에 따라서 Request 또는 RequestHeader 에서 제공되면 될 것 같습니다. 
1번의 경우도 
`request.getHeader().getContentType()` 가 
결국
```
RequestHeader requestHeader = request.getHeader();
requestHeader.getContentType();
```
인데, getter 를 어디서 제공할지보다 ContentType 이 어떻게 사용되는지에 따라 Request 나 RequestHeader 에 메시지를 보낼 수 있지 않을까요 ? 

예) `request.equalsContentType("json")`