[bryan.ko] 웹 서버 구현하기 Step1
2023newkrew/jwp-was-kakao pull request #35
Opened 2023-02-07 07:07 UTC by SJGeeKo

안녕하세요 맷, WAS 1차 미션 제출합니다.
이번 미션에서는 스프링 기반 미션들과는 또 다른 종류의 어려움을 겪었네요(제가 얼마나 HTTP와 WAS에 대해 무지한지 깨달을 수 있었습니다ㅠㅠ)

- `RequestHandler`: 기존에는 이 클래스가 모든 요청에 대한 처리를 하는 방식으로 구현되어 있었습니다. 저는 이 클래스가 프론트 컨트롤러 역할을 하도록 수정하였습니다.
- `HttpRequest`: BufferedReader가 읽은 문자열을 객체화하여 간편하게 뽑아 쓸 수 있도록 구현하였습니다.
- `ResponseHeader`: 리스폰스 헤더를 쉽게 구성할 수 있도록 작성한 클래스입니다.
    - 이 과정에서 `ContentType`, `HttpStatusCode` enum을 구현하였습니다.

리퀘스트 메서드가 무엇인지 확인하는 부분을 비롯해서 제거해야 하는 중복들이 보입니다만 결국 제출 기한 내에 해결하지 못했습니다🥲 이 부분들은 2단계 때 개선해보겠습니다.

이번에도 잘 부탁드립니다. 감사합니다 :)

2023-02-08 11:02 UTC, matt-jylee requested changes
전체적으로 잘 구성하셨습니다.
2단계를 위해서 선 머지 하고 2차에 좀 더 자세히 이야기 하도록 하겠습니다!

2023-02-08 11:02 UTC, matt-jylee commented on src/main/java/webserver/RequestHandler.java
> +        controllerMap.put("/user/create", new UserCreateController());
이 안에서 DBUtils 같은 것을 사용하게 되었는데 DB 관련 object도 주입 받는 방법을 고려해보는건 어떠실까요?

2023-02-08 11:02 UTC, matt-jylee commented on README.md
> +## 기능 요구사항
아래 이야기 나눈 것들을 써봤습니다.

주어진 코드에 관한 이해도와 문제점도 함께 생각해보기
ㄴ 동시에 1만개 요청이 들어와서 처리할 경우 어떻게 될까?
ㄴ thread 관점 - 연결의 비 효율 등...
ㄴ 실무 관점에서의 처리량 등 고민 해보기
인터페이스 설계 같은건 어떤 관점에서 바라보고 설계해야 할까 등 고민
실무에선 서버가 항상 잘 동작하고 오류가 발생해서 크래쉬 되면 안됨 => 예외 처리가 중요하다.
ㄴ 실무에선 내가 생각한 경로로만으로 동작하지 않는다.
파일을 읽게될 때 경로에 취약할 수 있으니 생각해보자.

2023-02-08 11:03 UTC, matt-jylee approved these changes

2023-02-08 11:03 UTC, merged

2023-02-09 01:16 UTC, SJGeeKo commented on src/main/java/webserver/RequestHandler.java
> +        controllerMap.put("/user/create", new UserCreateController());
네 그렇게 하는 편이 좋을 것 같네요. 반영하겠습니다 :)

2023-02-09 01:16 UTC, SJGeeKo commented on README.md
> +## 기능 요구사항
감사합니다. 할 수 있는데까지 반영해보도록 하겠습니다!