[hyun.k] HTTP 웹 서버 구현하기 1단계
2023newkrew/jwp-was-kakao pull request #6
Opened 2023-02-06 07:12 UTC by kimtaehyun98

안녕하세요 웨이드! 
드디어 마지막 미션이네요..! 마지막까지 잘 부탁드립니다 ☺️

### 구현 내용 
- Request Header를 분리하여 path에 해당하는 파일 읽어 응답
- Request Body를 분리하여 User객체 생성
- DispatcherServlet 역할을 하는 FrontController 구현
- HandlerMapping 구현(canHandle 메서드 구현)

2023-02-08 11:00 UTC, javajigi approved these changes
1단계 미션 진행하느라 수고했어요. 👍 
피드백 몇 개 남겼는데요.
다음 단계 진행할 때 함께 반영해 보세요.

2단계까지 마무리하고 유종의 미를 거두었으면 하는 바람으로 제가 대신 리뷰 진행해요.

2023-02-08 11:00 UTC, javajigi commented on src/main/java/controller/MyController.java
> +public interface MyController {
👍

2023-02-08 11:00 UTC, javajigi commented on src/main/java/webserver/WebServer.java
> +                frontController.addAll(new HomeController(), new UserController(), new StaticController());
이와 같이 구현할 경우 매 요청이 올 때마다 FrontController에 대한 초기화가 진행되기 때문에 성능이 떨어지지 않을까?
FrontController에 대한 초기화는 서버를 시작할 때 한번만 초기화하고 재사용 가능하도록 구현하는 것은 어떨까?

2023-02-08 11:01 UTC, merged

2023-02-09 04:19 UTC, wade-lim requested changes
리뷰를 너무 늦게해서 이미 머지돼버렸네요 ㅠㅠ
고생하셨습니다!

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/controller/FrontController.java
> +public class FrontController {
[의견]
클래스 이름이 `Controller` 라서 조금 헷갈리는 것 같아요~
여러 컨트롤러를 관리한다는 느낌의 이름으로 짓는건 어떨까요?

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/controller/FrontController.java
> +    }
[의견]
해당 요청을 handle 할 수 있는 컨트롤러를 반환하도록 수정하면 `handlerMapping` 에서 다시 한 번 컨트롤러를 찾을 필요가 없을 것 같아요~
또한 `FrontController` 에서는 컨트롤러를 찾는 일만 담당하도록 해서 클래스 간 종속도를 낮추는 것도 좋아보여요.
- `handlerMapping` 메소드 없이 바로 외부에서 반환된 컨트롤러에 대해 `Controller.handle()` 을 호출하도록 해도 괜찮을 것 같아요.
- 만약 선택된 컨트롤러에 대한 특수한 작업이 필요한 경우 `FrontController` 쪽에 구현하는 것보다 다른 클래스로 분리하는게 깔끔한 것 같습니다.

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/controller/HomeController.java
> +        }
[의견]
http response 를 생성하는 로직이 여러 곳에 중복돼서 나타나는 것 같아요!

스프링 부트와 비슷하게 `handle` 에서 `ResponseEntity` 를 반환하도록 하고, `ResponseEntity` 에는 response 를 구성, 저장, 응답 생성을 하도록 역할을 분리하면 좀 더 깔끔해질 것 같아요~

```java
// 간단하게 Builder 패턴 느낌으로 사용할 수 있습니다. (builder 클래스를 분리하는게 원칙적으로 좋긴 합니다.)
@Accessors(fluent = true, chain = true) 
@Setter
@RequiredArgsConstructor(staticName = "status")
public class ResponseEntity {
  private final int status = 200;
  private String contentType = "text/html";
  private byte[] body;

  public ResponseEntity body(String body) { ... } // string 형태의 body 입력

  public void response(DataOutputStream dos) { ... } // 입력된 데이터 바탕으로 응답 로직 작성
}
```

```
ResponseEntity.status(200)
  .contentType("text/html")
  .body(FileIoUtils.loadFileFromClasspath("templates" + headers.get("path")))
```

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/controller/HomeController.java
> +        return path.equals("/") || path.equals("/index.html") || path.equals("/favicon.ico");
[의견]
path 를 파싱할 수 있는 객체를 분리해보는 것도 좋을 것 같아요~

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/webserver/RequestHandler.java
> +        params.put("extension", getExtensionFromPath(path));
[의견]
params 는 request parameter 를 저장하는 용도인데, 여기에 extension 정보를 저장하는건 좋지 않은 것 같아요~
추가적으로 path 에서 확장자를 추출 할 수 있는데 extension 을 저장해야할 필요가 있을까요?

2023-02-09 04:19 UTC, wade-lim commented on src/main/java/webserver/RequestHandler.java
> +        headers.put("method", method);
[의견]
Http request message 포맷을 추상화한 `HttpRequest` 와 같은 객체를 만들고, 거기서 메세지를 파싱하도록 역할을 분리하는게 좋아보여요~
또한 `Content-Length`, `Accept` 도 일종의 헤더인데 요걸 헤더 객체로 변환하는 로직은 공통적으로 가져도 될 것 같아요.

2023-02-10 09:41 UTC, kimtaehyun98 reviewed
해당 리뷰들 반영하였고, 다음 단계 미션 PR에 남기도록 하겠습니다~!!

2023-02-10 09:41 UTC, kimtaehyun98 commented on src/main/java/controller/FrontController.java
> +public class FrontController {
FrontController를 만들 때, DispatcherServlet의 역할을 하게 하고 싶었기 때문에 DispatcherServlet으로 변경하였습니다!

2023-02-10 09:41 UTC, kimtaehyun98 commented on src/main/java/controller/FrontController.java
> +    }
코드를 다시 읽어보니 canHandle을 두 번 검사할 필요가 없었네요! Controller를 반환하도록 변경하였습니다.

2023-02-10 09:41 UTC, kimtaehyun98 commented on src/main/java/controller/HomeController.java
> +        }
Accessors를 찾아보고 공부해보았지만, 아직 적용하기엔 부족한 것 같아서 @Builder를 사용하여 Entity를 반환하도록 구현했습니다.
코드가 확실히 깔끔해졌는데, 웨이드가 말씀하신게 맞는진 잘 모르겠네요ㅠㅠ

2023-02-10 09:41 UTC, kimtaehyun98 commented on src/main/java/webserver/RequestHandler.java
> +        headers.put("method", method);
Request Handler 코드가 많이 지저분했었는데, 웨이드 말처럼 변경하니 많이 깔끔해졌습니다ㅎㅎ

2023-02-10 09:41 UTC, kimtaehyun98 commented on src/main/java/webserver/RequestHandler.java
> +        params.put("extension", getExtensionFromPath(path));
Extension 저장하지 않게 변경했습니다!