[leo.pss] 웹 서버 구현 step2 리뷰 요청 드립니다.
2023newkrew/jwp-was-kakao pull request #65
Opened 2023-02-09 08:34 UTC by HolywaterPark

안녕하세요 캐니!
이번 단계에서는 1단계에서 피드백 주신 부분과 2단계 요구사항 구현을 위주로 수정했습니다. 이번 과제는 스프링이 그리워지는 과제였던 것 같네요 😂 
벌써 마지막 과제네요 😁 지금까지 잘 리뷰해주셔서 너무 감사했습니다!!
이번에도 피드백 주시면 열심히 고쳐보도록 하겠습니다. 항상 감사합니다!!

2023-02-09 15:09 UTC, allstarkenny requested changes
안녕하세요 레오 😄 
코드를 보다보니 스프링이 그리워졌다는 레오의 말씀이 백번 이해가 갔네요 ㅋㅋ 🤣 
정상적으로 동작하는것 확인하였고 아래 자잘한 리뷰 드렸습니다.
매우 자잘한 리뷰들이니 보시고 수정해주시면 좋을거 같아요.

\+ 패키지를 크게 webserver와 아닌것으로 구분하신 이유도 궁금합니다. 🤔

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/db/DataBase.java
> +        if (users.containsKey(userId)) {
p4; 이 조건문이 없어도 정상 동작 할 것 같은데 기존 코드를 변경하신 이유가 있으신가요? 🤔

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/utils/ExistUserException.java
> +public class ExistUserException extends RuntimeException {
p3; Exception들도 별도의 패키지로 분리하면 더 파악이 쉬워질 것 같아요 😄

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/webserver/RequestHandler.java
> +        Controller controller = ControllerMapping.findByHttpRequest(httpRequest);
분리한거 너무 좋네요 👍

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/webserver/controller/ControllerMapping.java
> +public enum ControllerMapping {
오호 enum으로 구분하시다니 너무 좋습니다 👍

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/webserver/request/HttpRequest.java
> +        if (!headers.containsKey(headerKey)) {
p4; 이부분도 위에서 여쭤봤던 내용과 동일할 것 같네요. 😄

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/java/webserver/service/UserService.java
> +@NoArgsConstructor
p4; 불필요한 어노테이션 같네요

2023-02-09 15:09 UTC, kenny-kim2 commented on src/test/java/webserver/UserLoginRequestTest.java
> +    void LoginedButUserLogin() {
p3; 앗 대문자 😢

2023-02-09 15:09 UTC, kenny-kim2 commented on src/test/java/webserver/DefaultRequestHandleTest.java
> +    void socket_out() {
p3; 앗 스네이크 🐍 😢

2023-02-09 15:09 UTC, kenny-kim2 commented on src/test/java/webserver/DefaultRequestHandleTest.java
> +        // given
given, when, then 너무 좋네요 👍

2023-02-09 15:09 UTC, kenny-kim2 commented on src/test/java/webserver/UserListRequestHandleTest.java
> +        }
p3; 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다. 를 위반한 것 같네요 😢

2023-02-09 15:09 UTC, kenny-kim2 commented on src/main/resources/templates/user/register_failed.html
> +            <div class="alert alert-danger" role="alert">이미 등록된 아이디 입니다. 다시 시도해 주세요.</div>
p5; 뭔가 요 항목만 추가를 위하여 동일한 html을 추가하셨군요. 😄 
매우 쉬운 해결책일 수 있지만 추후에 페이지 변경이 발생하면 양쪽 다 바꿔줘야 하겠네요. 시간이 되신다면 기존 form.html을 활용해보는건 어떠신가요?

2023-02-10 04:51 UTC, HolywaterPark commented on src/main/java/db/DataBase.java
> +        if (users.containsKey(userId)) {
해당하는 키가 없으면 NullPointerException을 발생한다고 착각하고 있었습니다 😢 수정했습니다!!

2023-02-10 04:57 UTC, HolywaterPark commented on src/test/java/webserver/UserListRequestHandleTest.java
> +        }
테스트 코드라서 방심하고 있었네요 😱 이런 경우에 들여쓰기를 한 단계로 낮추려면 로직이 더 복잡해지고 비효율적으로 되는 것 같은데(제가 좋은 방법을 생각해내지 못한 것일 수도 있습니다), 현업에서는 이런 상황에서 어떻게 대처하게 되나요??

2023-02-10 05:28 UTC, HolywaterPark commented on src/main/resources/templates/user/register_failed.html
> +            <div class="alert alert-danger" role="alert">이미 등록된 아이디 입니다. 다시 시도해 주세요.</div>
이 부분은 handlebars를 이용하는 방법으로 해결할 수 있을 것 같습니다! form.html에 handlebars.java를 이용하여 등록 실패에 대한 div절에 조건문을 추가하고, form.html을 처음 호출할 때에 대한 컨트롤러를 추가하고 만약 실패한다면 다시 form.html을 OK 응답하는 방법이 있을 것 같은데, 더 좋은 방법이 있을까요?

2023-02-10 05:33 UTC, HolywaterPark commented
안녕하세요 캐니! 말씀해주신 수정사항 수정했습니다!
패키지의 경우는 스켈레톤 코드의 구성으로부터 파생되다보니 애매해진 것 같은데, http Request/Response와 관련된 로직들을 웹서버 패키지에 넣다보니 웹서버 패키지에 대부분 집중된 구조가 된 것 같습니다. 패키지를 분리하게 된다면 컨트롤러와 서비스를 밖으로 빼는 것이 좋을까요?
감사합니다!!

2023-02-10 12:47 UTC, allstarkenny requested changes
개인적으로는 말씀하신것과 같이 Controller와 Service를 밖으로 빼서 구성하면 좋을거 같습니다.
http Request/Response 만 남겨두고 나머지는 밖으로 나오는게 좋을거 같아요.

2023-02-10 12:47 UTC, allstarkenny commented on src/main/resources/templates/user/register_failed.html
> +            <div class="alert alert-danger" role="alert">이미 등록된 아이디 입니다. 다시 시도해 주세요.</div>
말씀하신 구조로 진행해봐도 좋을거 같습니다 👍

2023-02-10 12:47 UTC, allstarkenny commented on src/test/java/webserver/UserListRequestHandleTest.java
> +        }
아마 레오와 동일하게 두단계의 들여쓰기를 할 것 같아요. 🤫 😄 (3, 4 depth까지 가는 경우도 있...)
다만 이번 과제에서 규칙을 정해두었으니 최대한 맞춰보는 연습을 하시는거라고 생각하시면 좋을거 같습니다.

2023-02-10 12:50 UTC, allstarkenny commented on src/test/java/webserver/UserLoginRequestTest.java
> +        }
아! 추가 코멘트로 요런 로직은 stream을 최대한 써보시는것도 좋아보이긴 하네요 ㅎㅎ

2023-02-14 04:20 UTC, HolywaterPark commented
안녕하세요 캐니! 말씀해주신 부분 수정해 보았습니다.
Handlebars.java 관련 자료가 많이 없어서 헤매다가 생각보다 오래걸렸네요 😱
항상 감사합니다!! 😄

2023-02-14 05:38 UTC, allstarkenny approved these changes
그동안 고생 많으셨습니다~ 🙇 머지하도록 할께요.

2023-02-14 05:38 UTC, merged