[minion.mo] HTTP 웹 서버 구현하기 2단계
2023newkrew/jwp-was-kakao pull request #70
Opened 2023-02-09 09:44 UTC by gusah009

안녕하세요 조엘!

이번엔 step1 피드백과 아래와 같은 로그인 기능을 구현해봤습니다!

이번에도 잘 부탁드립니다! 🙇‍♂️🙇‍♂️🙇‍♂️

## Step2 기능 요구사항

- [x] 로그인 기능 구현
    - “로그인” 메뉴를 클릭하면 http://localhost:8080/user/login.html 으로 이동해 로그인할 수 있다.
    - 로그인이 성공하면 index.html로 이동하고, 로그인이 실패하면 /user/login_failed.html로 이동해야 한다.
    - 회원가입한 사용자로 로그인할 수 있어야 한다.
    - 자바 진영에서 세션 아이디를 전달하는 이름으로 JSESSIONID를 사용한다.
    - 서버에서 HTTP 응답을 전달할 때 응답 헤더에 Set-Cookie를 추가하고 JSESSIONID=UUID 형태로 값을 전달하면 클라이언트 요청
      헤더의 Cookie 필드에 값이 추가된다.
- [x] 템플릿 엔진 활용하기
    - 접근하고 있는 사용자가 “로그인” 상태일 경우(Cookie 값이 logined=true) 경우 http://localhost:8080/user/list 로 접근했을 때 사용자 목록을 출력한다. 만약 로그인하지 않은 상태라면 로그인 페이지(login.html)로 이동한다.
    - 동적으로 html을 생성하기 위해 handlebars.java template engine을 활용한다.
- [x] Session 구현하기
    - 쿠키에서 전달 받은 JSESSIONID의 값으로 로그인 여부를 체크할 수 있어야 한다.
    - 로그인에 성공하면 Session 객체의 값으로 User 객체를 저장한다.
    - 로그인된 상태에서 /user/login 페이지에 HTTP GET method로 접근하면 이미 로그인한 상태니 index.html 페이지로 리다이렉트 처리한다.

2023-02-13 08:44 UTC, haewon13 requested changes
고생많으셨습니다 미니언~ 
Session에 대한 관리를 lazyHolder 싱글톤 기법으로 처리한 점 좋습니다 👍 👍 
1단계에서의 RequestHandler의 확장 대응 피드백을 Controller interface와 HandlerMapper를 통해 다형성으로 풀어낸 점도 좋았는데요! service overriding은 유지한채 request url 매핑은 enum으로 관리하면 분산되어 있는 isMatch를 생략할 수 있을것 같아서 좋을것 같아요 (Nit)

그대로 머지해도 되는 정도지만 몇가지 보완하면 좋을 코멘트들이 있어서 Request changes로 할게요
2달 넘게 고생 많으셨습니다~!!

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/controller/Controller.java
> +    HttpResponseStatus getSuccessCode();
이건 setter 대신에 생성자 통해 초기화하도록 권장받으셔서 수정하신 것 같은데, 사실 전 ResponseUtil에서 각 200, 302별 응답 처리를 하고 있는데 이거와 별개로 각 controller마다 successCode를 정의해두고 해당 코드를 가져와 미리 세팅해두는게 관리 포인트가 분산되는 것처럼 보이네요..ㅎㅎ
이건 코딩 스타일에 따른 차이일것 같아요~ 전 각 controller에서 successCode 정의해두는것 보단 200,302에 따라 ResponseUtil에서 처리할때(기존 미니언의 방식) 처리하는게 깔끔해보여서 코멘트 남겨둡니다~ (리팩토링된 방식이 사실 기능이 확장됨에 따라 중복 코드가 많이 늘어날것처럼 보여서요)

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/response/HttpResponse.java
> +                dos.writeBytes("Set-Cookie: " + cookie.getName() + "=" + cookie.getValue() + "\r\n");
줄바꿈 개행문자들은 상수처리 해주시길 권장드립니다!

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/request/QueryStringParser.java
> +
= 없이 들어온 잘못된 요청일 경우에 대한 예외처리가 필요해 보입니다!
현재는 적합하지 않은 ArrayIndexOutOfBounds exception이 발생하고 있습니다

2023-02-13 08:44 UTC, haewon13 commented on src/test/java/webserver/RequestHandlerTest.java
> +    }
로그인 failure, rediect 테스트 코드 좋습니다! /user/list에 대한 인증 처리도 step2에서 같이 추가된 것으로 보이는데 추가된 기능에 대해서는 되도록 테스트 코드 작성해주세요 :)

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/security/SessionManager.java
> +        return LazyHolder.INSTANCE;
👍

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/security/Session.java
> +    }
현재 구조에서는 session에 대해서 id인 key와 values 세팅이 별도의 setter로 분리될 필요는 없어보여요!
생성자로 처리되면 좋을것 같습니다

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/request/QueryStringParser.java
> +        throw new RuntimeException();
별도의 메시지 없이 RuntimeException으로만 내리기에는 exception처리가 미흡해보입니다
bad request와 같이 처리하는건 어떠실까요?

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/handler/HandlerMapper.java
> +                .orElseThrow();
요청에 매핑되는 controller가 없을때 NoSuchElementException이 발생중인데 이 역시 bad request으로 처리됨이 적합해보이는데요 어떠실까요?

2023-02-13 08:44 UTC, haewon13 commented on src/main/java/webserver/controller/LoginController.java
> +        Session session = new Session(sessionKey);
sessionKey 생성을 Session 객체 내에서 하면 좀 더 명확한 역할 분리가 될것 같습니다~

2023-02-20 00:00 UTC, gusah009 commented on src/main/java/webserver/controller/Controller.java
> +    HttpResponseStatus getSuccessCode();
저도 이전 PR에서 커멘트를 받고 긴가민가했었는데, 스타일의 차이였네요! 좋은 리뷰 감사합니다! ㅎㅎ

2023-02-23 06:40 UTC, haewon13 approved these changes
피드백 반영해주시느라 고생하셨습니다! 
최종 머지할게요 :)

2023-02-23 06:40 UTC, merged