[ayaan.jun] 2단계 - 로그인 구현하기 리뷰 요청 드립니다!
2023newkrew/jwp-was-kakao pull request #77
Opened 2023-02-10 04:11 UTC by Neurumaru

안녕하세요, 헤이든
어느새 마지막 PR 입니다
그동안 바쁘신중에도 꼼꼼히 리뷰해 주셔서 감사합니다~!

이번에는 로그인을 하고 세션을 유지하는 것까지 구현을 했습니다.
진행을 하면서 자주 사용하는 Response에 대해서 간단하게 보낼 수 있도록 리펙토링도 진행했습니다.

마지막까지 잘 부탁드립니다!!

2023-02-13 10:04 UTC, hayden-ii requested changes
저야말로 이래저래 연초부터 일이 많아서 신경을 많이 못 써드렸는데 잘 따라와주셔서 감사합니다~ (_ _) 커맨트 몇가지 확인해주시고, 저도 마지막까지 잘 부탁드려요!

2023-02-13 10:04 UTC, hayden-ii commented on src/main/java/db/DataBase.java
> +    private static final Map<String, User> userIdIndex = new HashMap<>();
users와 userIdIndex 를 별도의 map으로 관리하는 이유가 있을까요?

2023-02-13 10:04 UTC, hayden-ii commented on src/main/java/db/DataBase.java
>          return Optional.of(autoIncrementId++);
addUser 함수는 동시에 불리는 경우가 발생하지 않는걸까요? autoIncrementId++ 를 해주는 시점과 autoIncrementId 값을 사용하는 시점이 다른데 문제가 될 여지가 없을지 확인해보면 좋을것 같아요~

2023-02-13 10:04 UTC, hayden-ii commented on src/main/java/was/handler/RequestHandler.java
> +            Object object = map.get(request.toPathPattern()).invoke(null, args.toArray());
object 구조체가 사용되고 있지 않은데 선언을 해준 이유가 따로 있을까요? 추가로 nullPointerException 발생하는것 확인 해주세요~

2023-02-14 10:18 UTC, Neurumaru commented on src/main/java/db/DataBase.java
> +    private static final Map<String, User> userIdIndex = new HashMap<>();
데이터베이스에서 id를 pk로 만들고 username을 index 생성해놓은 것과 유사한 느낌으로 별도로 관리했습니다.

2023-02-14 10:22 UTC, Neurumaru commented on src/main/java/db/DataBase.java
>          return Optional.of(autoIncrementId++);
synchronized를 사용해서 아예 함수를 동시에 호출하는 경우를 막아뒀는데, 리뷰 주신 부분을 생각해보니 autoIncrementId를 가져오는 부분을 따로 synchronized 함수 또는 lock을 통해서 최소화 하는것도 좋을것 같네요!

2023-02-14 10:25 UTC, Neurumaru commented on src/main/java/was/handler/RequestHandler.java
> +            Object object = map.get(request.toPathPattern()).invoke(null, args.toArray());
잘못된 중복코드였네요...! 이부분은 삭제하겠습니다! NullPointerException도 한번 확인해보겠습니다!

2023-02-14 11:15 UTC, Neurumaru commented
안녕하세요, 헤이든!
리뷰 주신 부분을 수정했습니다. 

인덱스 부분이 너무 임시로 만든 느낌이 들어 제거한 후에 find에서는 stream을 이용해서 탐색해서 찾았습니다.
그리고 Object부분은 아래 코드를 조금 더 좋은 코드로 바꿀 방법은 없을까 고민하다가 나온 중복코드라 삭제했습니다.
`return (Optional<Response>) map.get(pathPattern).invoke(null, args.toArray());`
또한 NullPointerException을 위에서 미리 확인 후에 함수가 실행되도록 변경했습니다.

헤이든 덕분에 많이 배워가는 것 같습니다!
마지막까지 리뷰 감사드립니다~!

2023-02-19 23:38 UTC, javajigi approved these changes
WAS 미션 재미있었나요? 
2단계 구현하느라 수고했어요. 👍 
과정 마무리하기 위해 제가 대신 merge해요.

2023-02-19 23:38 UTC, merged