[jayden.v] was 과제 step2
2023newkrew/jwp-was-kakao pull request #81
Opened 2023-02-10 05:43 UTC by Tarakyu

## 구현사항
- 로그인 기능 구현
  - 로그인 성공 시 Cookie에 session id 추가 후 index.html로 리다이렉트
  - 로그인 실패 시 login_failed.html로 리다이렉트
- 템플릿 엔진 활용
  - `http://localhost:8080/user/list`로 접근 시 로그인 여부 확인 후, 로그인 되어있으면 유저 리스트 표시
  - 로그인 되어있지 않으면 로그인 화면 리다이렉트
- Session 구현
  - Session Manager가 세션을 저장하고 불러올 수 있도록 구현 

## 느낀점
- 스프링의 방식을 따라서 컨트롤러가 뷰의 이름을 반환하도록 했는데 css와 같은 스태틱 파일들을 동시에 처리하는 게 어려웠다. 과제 요구사항에 맞춰서 HttpResponse를 반환하게 했으면 더 쉬웠을 것 같았습니다.
- 템플릿 엔진 활용 방법은.. 일단 더 깊게 공부하지는 않았습니다. 타임리프 정도는 쓸 수 있는데 과제에서 사용한 엔진은 꽤 어려웠습니다.
- 지금까지 리뷰 친절하고 꼼꼼하게 해주셔서 너무 감사드립니다! 덕분에 많이 배울 수 있었습니다. 🥹

2023-02-10 08:17 UTC, gogyzzz commented
안녕하세요 제이든~ 마지막 과제까지 고생 많으셨습니다~

시간 되는대로 하나씩 코멘트 드릴게요~

2023-02-10 08:19 UTC, gogyzzz commented
step 1 때 RequestHandlerTest 테스트가 실패했는데요, 이번에도 실패합니다 ㅠ
혹시 코드 수정해주신 부분이 반영되지 않은 건지.. 한번 더 확인 부탁드려요~

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/8141431/218038998-bfda06c7-60a4-4577-9b45-22f9248e5dff.png">

2023-02-10 09:16 UTC, gogyzzz commented on src/main/java/http/HttpHeader.java
> +        String cookieString = headers.getOrDefault(COOKIE, "");
크게 중요한 부분은 아닌데.. parse에서 null 처리를 하기 때문에 get만 써도 될 것 같습니다~

2023-02-10 09:29 UTC, gogyzzz requested changes
안녕하세요 제이든 ~ 기능 요구사항 잘 구현해주신 것 확인했습니다!

이전 과제에서 코멘트 드린 개선사항들이 코드에 부분부분 보이는 것 같아 더 코멘트 할 걸 찾기가 어렵네요 ㅎㅎ;

다른 리뷰어 분들의 코멘트도 참고하면서 같이 봤는데, 제이든이 작성해주신 코드에는 크게 해당하는 부분이 없었습니다. 
(컨트롤러에서 직접 html 경로를 참조하는 방식에 대해 책임 분리가 필요하다는 의견이 있었고, 
컨트롤러 매핑 시 키값을 enum으로 관리하는 의견 등이 있었습니다)

아주 자잘한 것만 코멘트 끄적여 봤어요!

주말 잘 보내세요~

2023-02-14 04:34 UTC, Tarakyu commented on src/main/java/http/HttpHeader.java
> +        String cookieString = headers.getOrDefault(COOKIE, "");
밖에서 예외처리를 하니 여기서는 default 값이 없어도 되겠네요!! 감사합니다

2023-02-14 04:34 UTC, Tarakyu commented
아무래도 디폴트 코드를 받아서 하다보니 리뷰를 반영해도 다음 주차에는 다시 원상복귀가 되어서 아쉽네요 😂
한 달간 꼼꼼하게 리뷰 봐주셔서 너무 감사드립니다!!

2023-02-14 05:39 UTC, merged