[asher.an] WAS 2차 미션
2023newkrew/jwp-was-kakao pull request #83
Opened 2023-02-10 06:40 UTC by mkom76

2차 미션은 로그인 기능을 구현하는 것이 목적이었습니다.
처음에는 쿠키만을 가지고 로그인을 구현하는 것이 목표였고, 현재 코드는 세션을 추가하여 세션 로그인을 구현해둔 상태입니다.

auth 패키지 **(2차에 추가)**
- AuthUtils: 세션이 유효한지 확인하는 함수가 있습니다.
- HttpCookie: 쿠키 객체입니다. UUID를 객체를 받아서 String으로 저장됩니다. 모든 path에 대해 요청하도록 path는 디폴트값인 / 입니다.
- Session: 로그인한 유저에 대한 세션 객체입니다. 세션에 여러 가지 유저 정보를 넣을 수 있도록 Map을 사용하였으나, 저는 userObject를 key로 하여 유저 객체 자체를 저장하였습니다(현재 제 구현상 Map이 큰 의미가 없습니다). 
- SessionManager: 여러 클라이언트에서 서로 다른 유저가 로그인할 수 있기 때문에, Session을 저장하고 관리하는 객체를 만들었습니다.

webserver 패키지
- WebServer: 웹서버 어플리케이션입니다. 포트설정, 소켓 및 커넥션 등을 설정하고 구동하는 부분입니다.
- RequestHandler: 클라이언트 요청을 받아서 적절한 응답을 반환하는 클래스입니다. 리팩토링 과정에서 로직을 최소화하여 컨트롤러 느낌으로 - 구현하였습니다.
- PathBinder: HTTP 요청 URL을 분석하여 각 URL에 적절한 메소드를 실행할 수 있게 합니다.

utils 패키지
- FileIoUtils: 파일입출력을 도와주는 클래스입니다. path에 해당하는 파일을 읽어오는 메소드가 있습니다.
- IOUtils: HTTP Header, Body를 String으로 받을 수 있게 도와줍니다.
- LogicValidatorUtils: 비즈니스 로직에서 예외사항이 나는 부분들을 핸들링해줍니다. split의 NPE를 방지하기 위해 만들었습니다.
- ResponseUtils: http response code에 맞는 response문을 만들어줍니다. 헤더와 바디를 만드는 메소드가 따로 있습니다.

supports 패키지
- HttpParser: HTTP 요청의 Header를 파싱하여 정보를 해시맵에 담아둡니다.
- UserService: 회원가입 할 때 User를 DB에 넣기 위한 로직을 구현하였습니다.
- SplitMethodException: 스플릿 로직에서 에러가 났을 때 발생합니다.
- TemplateService **(2차에 추가된 클래스)**: 템플릿 엔진을 사용하여 서버에 있는 유저정보를 html에 적용시키기 위해 만들었습니다. handlebar를 사용하여 html을 동적으로 만들고 바디에 반환합니다.

model 패키지
- User: 유저 도메인입니다.

db 패키지
- DataBase: 유저 정보가 id를 키로 하는 해시맵에 담겨있습니다. DAO 로직이 구현되어있습니다. 데이터베이스 연결은 없습니다.

특이사항:
1. pathbinder 리팩토링은 못했습니다..ㅠㅠ 세션 개념을 이해하는데 생각보다 오래 걸려서 구현만 마치고 제출했습니다.
2. 로그아웃 기능은 현재 구현되어있지 않습니다. 요구사항에 없어서 그런지 request문이 안날라오더라구요..
3. 로그인이 된 상태에서 로그인 버튼을 누르면 index로 리다이렉트되는 부분을 구현하지 못했습니다. 객체 역할구분을 제대로 못해서 고치려면 1번 리팩토링과 함께 진행해야 할 것 같습니다.
4. Session, SessionManager에 구현된 메소드들은 스펙에 있는 스켈레톤코드를 구현하여, 사용하지 않는 함수도 있습니다.
5. 홈페이지에서 직접 테스트해서 테스트코드를 잘 짜지 못했습니다. 테스트코드도 많이 추가하려했지만.. 시간부족으로 일단 요청 드립니다.

너무 부족한 코드 리뷰드리는 것 같네요..ㅠㅠ 죄송합니다. 항상 감사합니다!

2023-02-13 02:55 UTC, scolleck commented on src/main/java/auth/HttpCookie.java
> +        return "JSESSIONID=" + this.cookie.toString() + "; Path=" + this.path;
this.cookie 가 String인데 toString()은 생략되어도 되지 않을까요? :)
(IDE에 의해 자동생성된것일수도..?)

2023-02-13 04:56 UTC, scolleck requested changes
고생하셨습니다. 몇가지 리뷰사항 남겨드렸습니다.

2023-02-13 04:56 UTC, scolleck commented on src/main/java/auth/HttpCookie.java
> +        return "JSESSIONID=" + this.cookie.toString() + "; Path=" + this.path;
this.cookie 가 String인데 toString()은 생략되어도 되지 않을까요? :)
(IDE에 의해 자동생성된것일수도..?)

2023-02-13 04:56 UTC, scolleck commented on src/main/java/auth/Session.java
> +    private final ConcurrentHashMap<String, User> values = new ConcurrentHashMap<>();
ConcurrentHashMap 💯

2023-02-13 04:56 UTC, scolleck commented on src/main/java/model/User.java
> +    }
[Nit]
보통 password와 같은 값은 trim을 하여 저장하고, 비교대상 파라미터도 trim 처리를 같이 해줍니다 :)

2023-02-13 04:56 UTC, scolleck commented on src/main/java/auth/SessionManager.java
> +    public static Session findSession(String id) {
SessionManager내 메소드들이 받는 파라미터 id는 원래 과제상 UUID로 확인되는데요,
코드를 보면 cookieString 인것처럼 보입니다.

이에 맞추어 파라미터 네이밍을 바꾸거나, 파라미터에 올바른 값을 넣어주는것은 어떨까요?

2023-02-13 04:56 UTC, scolleck commented on src/main/java/supports/TemplateService.java
> +    private byte[] getUserProfileTemplate(HttpParser httpParser) throws IOException, URISyntaxException {
메소드명을 보면 Template을 반환할것으로 기대되나 실제로는 html의 인코딩된 바이트코드를 넘겨주고있는것 같습니다.
리턴타입을 수정하거나, 메소드명을 수정해주면 어떨까요?

2023-02-13 04:56 UTC, scolleck commented on src/main/java/supports/UserService.java
> +            return null;
null을 리턴하는것은 좋지 않은 설계가 될 수 있습니다.
아래 링크를 참조하시어 null보다는 다른 방안을 찾아보면 어떨까요?

https://www.yegor256.com/2014/05/13/why-null-is-bad.html

2023-02-13 04:56 UTC, scolleck commented on src/main/java/auth/Session.java
> +public class Session {
해당 객체의 이름이 Session 이 맞을까요? Sessions 가 맞을까요?

2023-02-13 04:56 UTC, scolleck commented on src/main/java/utils/LogicValidatorUtils.java
> +            logger.error("split 대상이 null입니다.");
👍

2023-02-13 04:56 UTC, scolleck commented on src/main/java/webserver/PathBinder.java
> +        }
하나의 메소드에 다수의 로직이 포함되어있어 메소드 추출로 리팩토링이 필요하지 않을까 싶습니다

2023-02-14 01:18 UTC, mkom76 commented on src/main/java/auth/HttpCookie.java
> +        return "JSESSIONID=" + this.cookie.toString() + "; Path=" + this.path;
처음 구현할 때 UUID로 선언했다가 리팩토링 과정에서 String으로 변경했었는데 그 과정에서 놓친 것 같네요.. 확인 감사합니다!

2023-02-14 01:48 UTC, mkom76 commented on src/main/java/model/User.java
> +    }
헉 전혀 몰랐습니다.. 좋은 내용 감사합니다!!

2023-02-14 10:01 UTC, mkom76 commented on src/main/java/supports/TemplateService.java
> +    private byte[] getUserProfileTemplate(HttpParser httpParser) throws IOException, URISyntaxException {
아하 그렇네요. 템플릿을 만진다는 생각에 이렇게 한 것 같네요.. 최종 리턴값 항상 생각해봐야겠습니다!ㅎㅎ html로 변경했습니다!

2023-02-14 10:04 UTC, mkom76 commented on src/main/java/auth/Session.java
> +public class Session {
이 객체는 Session이 맞는 것 같습니다! Session객체들을 관리하는 객체 이름이 SessionManager고, 이 안에 멤버변수로 선언되어 있는 해시맵을 sessions로 정의하였습니다.
Session 객체에서는 로그인한 유저의 각종 정보들을 담는 해시맵 values를 유지하고 있습니다!

2023-02-15 04:39 UTC, mkom76 commented on src/main/java/webserver/PathBinder.java
> +        }
if문 안의 로직을 MethodAndPathCheckUtils로 분리시켰습니다. 추가적으로 TemplateService의 로직도 TemplatePathCheckUtils로 분리시켰습니다!

2023-02-15 06:04 UTC, scolleck commented on src/main/java/webserver/PathBinder.java
> +        }
util도 좋지만, 단순 분기처리는 클래스 내부에서 private 메소드로 추출하는것도 좋습니다 :)

2023-02-15 06:05 UTC, scolleck approved these changes
고생많으셨습니다~

2023-02-15 06:05 UTC, merged