[hyun.k] WAS 구현 2단계
2023newkrew/jwp-was-kakao pull request #84
Opened 2023-02-10 09:52 UTC by kimtaehyun98

안녕하세요 웨이드~!! 드디어 마지막 코드리뷰네요 ☺️
지금까지 모든 리뷰 정말 많은 도움이 되었고 다시 한번 정말 감사합니다..!
나중에 파트에서 뵙게 되면 인사드릴게요~!!

## 구현 내용 
로그인 기능 구현(쿠키를 사용한 로그인 성공 및 실패 로직 분리)
템플릿 엔진(handlebars)를 사용한 userList view 구현
세션 구현

## 기타
1단계 미션에서 받았던 리뷰를 바탕으로 리팩토링을 진행하였습니다.

코드를 구현하면서 가장 고민했던 부분은 UserController path 매칭 부분을 어떤 방식으로 리팩토링해야 하나였습니다.
결국엔 지금 코드처럼 Method와 URL을 바탕으로 로직을 분리했지만, 더 좋은 방법이 있을지 궁금합니다!

2023-02-14 07:54 UTC, wade-lim requested changes
고생하셨습니다~

코드 컴파일 중 에러가 발생하는 부분이 있던데 요것도 같이 확인 부탁드립니다~

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/controller/DispatcherServlet.java
> +}
[의견]
Spring 구조와 비슷하게 구현해주셨군요 👍

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/webserver/request/HttpRequest.java
> +public class HttpRequest {
[의견]
요청을 깔끔하게 추상화 해주셨네요 👍

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/controller/UserController.java
> +    private byte[] body = null;
[확인]
request 단위로 수정이 발생하는 필드를 가지고 있는 경우 동시성 문제가 발생할 것 같아요~
해당 변수를 지역변수화 시키거나 클래스로 이동, 메소드 분리 등으로 처리하도록 해야할 것 같습니다.

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/controller/UserController.java
> +                .build();
[의견]
switch 성격의 if 문은 해당 조건을 만족하면 바로 함수를 종료하는게 좋아보여요.
예기치않게 이전 조건문과 이후 조건문이 동시에 만족하여 실행되는 실수가 종종 있어서 바로 return 을 해주는게 좋아보입니다.

또한 if 문 만족시 실행되는 함수들(createForm, loginForm, ...) 은 Spring Controller 로 따지면 각각이 @GetMapping, @PostMapping 된 함수라고 볼 수 있는데 해당 함수들은 동일 파라미터 타입, 리턴 타입을 가지도록 하는 것이 더 직관적인 것 같아요~

ex) ResponseEntity createForm(HttpRequest request)

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/controller/MyController.java
> +    ResponseEntity handle(HttpRequest httpRequest, DataOutputStream dataOutputStream);
[의견]
DataOutputStream 이 사용되는 곳이 없는 것 같은데 제외해도 괜찮지 않을까요?

2023-02-14 07:54 UTC, wade-lim commented on src/main/java/model/dto/Cookie.java
> +    }
[의견]
JSESSIONID 와 관련 없는 Cookie 가 있을 수도 있는데, 현재 구조는 JSESSIONID 와 너무 강하게 결합된 것 같아요~

2023-02-15 09:00 UTC, kimtaehyun98 commented on src/main/java/controller/UserController.java
> +    private byte[] body = null;
코드를 다시 읽어보니 동시성 문제를 고려하지 못했네요ㅠㅠ
이 부분은 아래 리뷰와 같이 모든 메서드들이 ResponseEntity를 반환하게 하여 전역 변수들을 삭제하였습니다.

2023-02-15 09:00 UTC, kimtaehyun98 commented on src/main/java/controller/UserController.java
> +                .build();
이 부분은 위의 리뷰와 같이 수정하여 모든 메서드들이 ResponseEntity를 반환하도록 하였습니다.
확실히 코드가 많이 깔끔해졌네요! 👍👍👍

2023-02-15 09:01 UTC, kimtaehyun98 commented on src/main/java/model/dto/Cookie.java
> +    }
확장성을 생각하지 못했네요..!
이 부분은 toString()을 모든 파라미터를 불러오는 식으로 변경하였습니다!

2023-02-15 09:01 UTC, kimtaehyun98 commented
앗 이번에도 merge conflict를 해결을 제대로 안했었네요ㅠㅠ 죄송합니다 😭
말씀해주신 부분들 반영해서 수정 완료하였습니다.

긴 기간동안 부족한 코드 열심히 봐주시고 리뷰해주셔서 정말 감사합니다!
웨이드 덕분에 코드 리뷰가 얼마나 중요한지 알 수 있었고, 몰랐던 부분들을 많이 배울 수 있었습니다.
회사에서 뵙게 되면 꼭 인사드릴게요! 다시 한번 감사합니다~!! 🙇🏻‍♂️

2023-02-16 05:31 UTC, wade-lim approved these changes
마지막까지 고생 많으셨습니다 😁
리뷰 기간 동안 제 때 리뷰를 못 드린 경우도 많은데 리뷰가 조금이라도 도움이 되셨다면 좋겠네요~

2023-02-16 05:31 UTC, merged