[marcus.min] 웹 서버 구현하기 2단계
2023newkrew/jwp-was-kakao pull request #85
Opened 2023-02-10 10:23 UTC by ekzm8523

안녕하세요 웨이드!!
드디어 마지막 미션이네요 ㅠㅠ 정말 고생 많으셨구 감사드려요.

[과제 링크](https://edu.nextstep.camp/s/GiKTqpMP/ls/bNcb1y8J)

### 특이 사항
지난 리뷰에서 말씀주신 빌더패턴을 Response에만 적용하였습니다.
> Request에서는 parsing할때 빼고는 생성을 하지 않기 때문에 유동적으로 만들어야 하는 Response에만 만들어주었습니다.

HttpRequestHeader & HttpResponseHeader를 객체화 하였습니다.

나머지는 과제 요구사항에 맞도록 개발하였습니다.
마지막까지 잘 부탁드립니다!! 🙇

2023-02-14 09:06 UTC, wade-lim requested changes
마지막까지 고생하셨습니다~

코드가 깔끔해서 많이 리뷰 드릴 부분이 없네요 😁

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/model/User.java
>      }
[의견]
요건 lombok @ToString 에서 지원해줄거에요~

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/model/User.java
> +    }
[질문]
사용되지 않는 함수인 것 같은데 어떤 목적의 함수인가요?

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/utils/TemplateEngine.java
> +        handlebars = new Handlebars(loader);
[의견]
Template 관련 라이브러리가 있나보네요~ 👍

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/webserver/handler/LoginListHandler.java
> +        if (request.getHeaders().getCookie().get("JSESSIONID") != null) {
[질문]
Cookie.get(key) 는 항상 null 이 아닌 값을 반환하는 것 같은데 요 조건을 만족하는 경우가 있나요?

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/webserver/request/HttpRequestHeader.java
> +    }
[의견]
해당 기능은 여러 라이브러리에서 기본적으로 제공하는 기능이라 그걸 이용하는 것도 좋을 것 같네요~
현재 디펜던시로는 `StringUtils.isEmpty()` 를 사용할 수 있을 것 같습니다.
혹은 해당 기능을 지원하는 라이브러리가 없다면 따로 유틸리티 클래스를 만들어서 분리시키는게 좋을 것 같아요~

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/webserver/response/HttpResponse.java
> +public class HttpResponse {
[의견]
깔끔하네요 👍

2023-02-14 09:06 UTC, wade-lim commented on src/main/java/webserver/response/HttpResponseHeader.java
> +    }
[의견]
자주 쓰이는 헤더들에 대해 기본적으로 제공하니까 편리한 것 같네요~

2023-02-16 23:25 UTC, ekzm8523 commented on src/main/java/model/User.java
> +    }
아 요구사항중에 아래와 같은 요구사항이 있어서 추가했는데요! 
생각해보니 memory database 형태이기 때문에 User 객체를 그대로 저장하였습니다 😭 지금은 레거시네요 제거하겠습니다!
>로그인에 성공하면 Session 객체의 값으로 User 객체를 저장해보자.

2023-02-16 23:28 UTC, ekzm8523 commented on src/main/java/webserver/handler/LoginListHandler.java
> +        if (request.getHeaders().getCookie().get("JSESSIONID") != null) {
아 제가 getOrDefault를 사용하였네요 !!
isBlank로 변경하였습니다 😊

2023-02-16 23:30 UTC, ekzm8523 commented on src/main/java/webserver/request/HttpRequestHeader.java
> +    }
앗 `StringUtils.isEmpty()` 와 변수명 빼고는 정확히 일치하네요!! ㅋㅋㅋㅋ 변경하였습니다 😊

2023-02-16 23:32 UTC, ekzm8523 commented on src/main/java/model/User.java
>      }
의견 감사합니다!!
다만 현재 lombok 라이브러리를 사용하고있지 않아서 다음번부터는 lombok 을 적극 활용하도록 할게요 👍👍

2023-02-16 23:36 UTC, ekzm8523 commented
@wade-lim 제가 이사를 한다고 정신이 없어서 리뷰 반영을 너무 늦게 했네요 😭
7주라는 긴 기간동안 정말 많은걸 배웠어요!! 감사드립니다 🙇🙇
업무랑 병행하시느라 힘드셨을텐데 저번 회식때 고기를 못 구워드린게 자꾸 생각나더라구요.. 다음번엔 제가 손수 구워 올려드리겠습니다 😄

2023-02-17 05:54 UTC, wade-lim approved these changes
마지막까지 고생 많으셨습니다 😁
리뷰 기간 동안 제 때 리뷰를 못 드린 경우도 많은데 리뷰가 조금이라도 도움이 되셨다면 좋겠네요~

2023-02-17 05:54 UTC, merged